### ISSUE TITLE
Does not provide expected consumption rate for Space Age Biolabs

### ISSUE THREAD

**Issue by klardotsh** [raiguard/RateCalculator#183] opened 2024-12-17 07:21 UTC
### Description

RC does not appear to account for the science pack drain modifier - it claims that our (friend and I's server) new Biolab-based science factory should be consuming about 2x as many science flasks as it actually does (with the net effect that we built about 2x too small of a science outpost as we needed to consume all the inbound flasks, particularly from Gleba which spoil). Biolabs drain flasks ~2x more slowly than a base Lab, it would be great if RC could accomodate this in calculations!

**Comment by raiguard** [comment] 2024-12-19 02:30
This is going to require an API addition to fix.

**Comment by raiguard** [comment] 2024-12-19 03:07
Duplicate of #169

**Closed by raiguard** 2024-12-19 03:07 UTC
Labels: bug
