### ISSUE TITLE
Wrong steam consumption on higher quality steam turbines

### ISSUE THREAD

**Issue by TheGaijin87** [raiguard/RateCalculator#176] opened 2024-11-22 00:31 UTC
### Description

was trying to plan for a nuclear power plant with 2x10 and when calculating everything by hand i get 304 heat exchangers that can fill 522(.5) steam turbines. when checking with rate calculator the heat exchangers show the correct 3 mil and a few k steam generated but when checking one half of the steam turbine side with 261 rare (blue) machines it shows only a use of 936k instead of the 1.5 mil it should have. when checking stats it seems rate calculator calculates with 60 steam/s per steam turbine while rare has 96 steam/s. im assuming quality is not regarded for steam turbines (for whatever reason)

### Reproduction

build higher quality steam turbine, check rate calculator usages / second with actual usage / second

**Comment by raiguard** [comment] 2024-12-04 04:46
This will require a new API feature to fix. so it'll be a while.

**Comment by raiguard** [comment] 2024-12-04 04:52
Duplicate of #168.

**Closed by raiguard** 2024-12-04 04:52 UTC
Labels: bug
