### ISSUE TITLE
[Feature Request] limit products based on intermediates

### ISSUE THREAD

**Issue by andrei9669** [raiguard/RateCalculator#136] opened 2023-09-24 13:53 UTC
### Description

Would it be possible to have a button/option that would limit the production and intermediate outputs based on the limitations of other intermediates, to get the true rate, since it already sort of shows the +/- of intermediates?

**Comment by raiguard** [comment] 2023-09-25 15:39
Duplicate of #130, #121, and many others.

**Closed by raiguard** 2023-09-25 15:39 UTC
